spring.mvc.view.prefix: /
spring.mvc.view.suffix: .html
application.message: Hello World

server:
  port: 8000  
 
###
spring:
    datasource:
        name: test
        url: jdbc:mysql://172.17.3.105:3306/uranus?useUnicode=true&characterEncoding=utf-8&useSSL=false
        username: root
        password: kingdee
        # 使用druid数据源
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.jdbc.Driver
        filters: stat
        maxActive: 20
        initialSize: 1
        maxWait: 60000
        minIdle: 1
        timeBetweenEvictionRunsMillis: 60000
        minEvictableIdleTimeMillis: 300000
        validationQuery: select '1'
        testWhileIdle: true
        testOnBorrow: false
        testOnReturn: false
        poolPreparedStatements: true
        maxOpenPreparedStatements: 20
    elastic: 
      host1: 172.17.4.96
      port1: 9300
      host2: 172.17.4.95
      port2: 9300
      host3: 172.17.4.94
      port3: 9300       
    servlet:
      multipart:
      # 上传一个文件最大值,默认1Mb
        max-file-size: 100MB
      # 上传多个文件最大值,50Mb,默认10Mb
        max-request-size: 500MB


spring.redis.database: 0
spring.redis.host: 172.17.4.94
#spring.redis.url: 172.17.51.97
spring.redis.port: 7000
           
mybatis:
  mapper-locations: classpath*:mapper/**/*.xml
  type-aliases-package: com.kingdee.uranus.mapper
  typeHandlersPackage: com.kingdee.uranus.handler 

#pagehelper分页插件
pagehelper:
    helperDialect: mysql
    reasonable: true
    supportMethodsArguments: true
    params: count=countSql
          
logging.config:
     classpath:logback.xml
     
login.forward.url: 
      //172.19.85.126:8000/login.html           
          
 #DMP HOST     
dmp.host: http://192.168.16.18/           